export const Products = [
  {
    id: "1",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "2",
    name: "Dell Notebook 15 latitude 5550 RGB Silver",
    brand: "Dell",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images:
      "/Assets/laptops/notebook-latitude-15-5550-rgb-silver-gallery-20-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "3",
    name: "Dell Notebook Alienware x16 r2 gray",
    brand: "Dell",
    category: "Gaming",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images:
      "/Assets/laptops/dell-notebook-alienware-x16-r2-gray-gallery-12.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "4",
    name: "Omen Transcend Laptop-14 120Hz 3K",
    brand: "Hp",
    category: "Gaming",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/omen-Transcend-Laptop-14-120Hz-3K.webp",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "5",
    name: "Omen Transcend Laptop-16 ",
    brand: "Hp",
    category: "Gaming",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/omen-Transcend-Laptop-16.webp",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "6",
    name: "HP Elitebook XFlip G1i 14inch",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images:
      "/Assets/laptops/HP-Elitebook-X-Flip-G1i-14inch-Notebook-business.webp",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "7",
    name: "Hp Laptop 17t-cn300 17.3",
    brand: "Hp",
    category: "Student",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "8",
    name: "Hp Notebook Inspiron-14 7440-t ice blue",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images:
      "/Assets/laptops/notebook-inspiron-14-7440-t-ice-blue-gallery-4-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "9",
    name: "Dell Notebook g15 5535-nt black",
    brand: "Dell",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/dell-notebook-g15-5535-nt-bk-gallery-4.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "10",
    name: "Dell Laptop Alienware m18 r2 hd perkey intel black",
    brand: "Dell",
    category: "Gaming",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images:
      "/Assets/laptops/dell-laptop-alienware-m18-r2-hd-perkey-intel-bk-gallery-2.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "11",
    name: "Dell g16 Gaming Laptop",
    brand: "Dell",
    category: "Gaming",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/dell-g16-gaming-laptop.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "12",
    name: "Dell Notebook Inspiron-15 3520 Black",
    brand: "Dell",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images:
      "/Assets/laptops/notebook-inspiron-15-3520-black-gallery-4-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "13",
    name: "Dell Notebook 15 latitude 3550 Gray",
    brand: "Dell",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images:
      "/Assets/laptops/notebook-latitude-15-3550-gray-gallery-2-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "14",
    name: "Dell Alienware-m16 R2",
    brand: "Dell",
    category: "Gaming",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/dell-alienware-m16-R2-Gaming-Laptop.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "15",
    name: "Hp Probook x360 435",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-probook-x360 435-business.webp",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "16",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "17",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
  {
    id: "18",
    name: "MacBook Pro 16-inch M2",
    brand: "Hp",
    category: "Business",
    price: 2499,
    description: "Powerful M2 chip, 16-inch Retina display, 32GB RAM.",
    configorations: {
      processor: "Apple M2 Pro",
      ram: "32GB",
      storage: "1TB SSD",
      graphics: "M2 Pro Integrated GPU",
      display: "16-inch Retina, 3456x2234",
      battery: "Up to 21 hours",
      weight: "2.1kg",
      operatingSystem: "macOS Ventura",
    },
    images: "/Assets/laptops/hp-EliteBook-665-16-inch-G11-business.png",
    stock: 15,
    isNewArrival: true,
    ratings: {
      average: 4.8,
      totalReviews: 120,
    },
  },
];